
# Включение тайтлов

Enable: true

# Надписи ; Используйте "§<число/буква>"текст" "§4Смэрт"
# Цветовые Коды:
# §1 - темно-синий ; §2 - темно-зеленый
# §3 - темно-голубой ; §4 - темно-красный
# §5 - темно-фиолетовый ; §6 - золотой
# §7 - серый ; §8 - темно-серый
# §9 - синий ; §0 - черный
# §b - голубой ; §c - красный
# §d - фиолетовый ; §f - белый
# §e - желтый ; §a - зеленый
# §r - сброс ; §l - жирый
# §o - курсив ; §n - подчеркивание
# §m - зачеркнутый ; §k - вечно меняющиеся буквы(шифр)

Title: "§4Смэрт"
Subtitle: "§aЖивчик"

# Эффектс
  # Stay - продолжительность надписи
  # In - появление надписи
  # Out - пропажа надписи

Stay: 10
In: 10
Out: 10

# Звук:
# звуки можно взять с: https://gist.github.com/Andre601/1ab3b4fabd0010ae241156333491c379

Sound: BLOCK_ANVIL_BREAK